### PR TITLE
Fix acc tests on ovh_domain_zone_redirection

### LINKED ISSUE #37: acc tests are failing on TestAccOvhDomainZoneRedirection_*
acc tests file have been copied/pasted
with a remaining "ttl" attr which is not accepted by the ovh_domain_zone_redirection resource

### PR DESCRIPTION
**Pull request by yanndegat**
Closes #37

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @dlecan

i had to fix acc tests on this resource

could you double check it pls?

**Comment by dlecan** [comment]
@yanndegat what kind of test?

**Comment by yanndegat** [comment]
actually all acc tests you had submitted earlier on this resources were failing for various reasons
my guess is that maybe you ran only "make test" and not "make testacc" :)

tests that are prefixed by testAcc are acceptance tests, which arent run on every pr as they can generate a lot of costs on the underlying cloud platforms

**Comment by dlecan** [comment]
@yanndegat 
> maybe you ran only "make test" and not "make testacc" :)

Yes, I didn't run `testacc` for the same reason you wrote: I think it can generate lot of costs. I don't know if can run them myself for free.

I look at your code, everything seems allright.

**Comment by yanndegat** [comment]
great

fyi you can run only your own tests.
for instance, on the domain zone, it wouldnt generate costs

ill merge the pr then

thanks for the review

**Pull request merged**
