### PR TITLE
Add ovh_iploadbalancing_http_route resource

### PR DESCRIPTION
**Pull request by eliecharra**
Sorry OVH related doc is only in french ... https://docs.ovh.com/fr/load-balancer/routes/

- [x] Handle deletion from state when response is 404
- [x] Add ovh_iploadbalancing_http_route_rule resource
- [x] Fix acc tests
- [x] Doc

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @eliecharra 

thanks a lot for this job

i have a few questions:
- why are you sorry for the docs ? the doc entries you've added seems to be correct no?
- what's the acc test issue ? do you need any help with that?

**Comment by eliecharra** [comment]
> why are you sorry for the docs ? the doc entries you've added seems to be correct no?
Doc written in french, docs should be redacted "english first" in mind as french is not so open source compliant imho ... but this is a detail ;-)

> what's the acc test issue ? do you need any help with that?
I havent finished writing tests cases yet, maybe I'll need some help afterwards.
Is Travis now configured to use the load balancer instance ?

> could you rebase your PR according to the last merges on master ?
 Sure !

**Comment by eliecharra** [comment]
@yanndegat Actually acc test are not launched by Travis, did you plan to configure them ?

I'd like to cover this resources with acc test if possible

**Comment by yanndegat** [comment]
hi @eliecharra 

i have to sync with @tombuildsstuff 
it should be ready soon now

**Comment by eliecharra** [comment]
Ok, let me know when evrything is ready, I'll try to run my tests on it.

**Comment by yanndegat** [comment]
hi @eliecharra 
i don't know what you mean by running your tests on it. 
The tests acc are run by hashicorp team city ci. i dont think you have access to their ressources
am i correct?

**Comment by eliecharra** [comment]
acc test should be setup to run on every PR imho.

The openstack provider, for example, is running openlab CI on every pull request https://github.com/terraform-providers/terraform-provider-openstack/pull/261

By running my test on it, I mean on this pull request through a continous integration process.

**Comment by yanndegat** [comment]
well the openstack provider is different from other cloud providers in a sense that there's no real cloud provider thus billed infrastructure behind.

imagine you'd made a PR on a compute resource that mines bitcoins... 
you have to check your acc tests before i can merge it 
otherwise i have to fix them afterwards ( as im currently doing on another PR :( btw )

**Pull request merged**
