### PR TITLE
Add a datasource for vps (on the dedicated_server model)

### PR DESCRIPTION
**Pull request by gaetanfl**
This is the first step to have feature parity between vps and dedicated servers.

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @gaetanfl 

thank you very much for contributing this new feature

it's seems to me though that the tests are failing.

are they passing on your side ?

**Comment by gaetanfl** [comment]
You're right, it's now fixed

**Comment by gaetanfl** [comment]
Hi @yanndegat is there anything I can do to help this PR be merged ?

**Comment by yanndegat** [comment]
hi @gaetanfl 

firstable thank you so much for all the time you spent contrubuting this new resource.

i just have to find some time to try to run the testacc but to do so, i have to order a VPS, 
and then make the review.

i dont have much time for now, but i'll try to do so in the next couple weeks 

can you wait a few more weeks ?

**Comment by gaetanfl** [comment]
Sure, it can wait a few weeks, I can produce the binary and use it on my side

**Comment by gaetanfl** [comment]
Hi @yanndegat , I finally took the time to test it with my inventory and it works fine. Did you have time on your side to do some tests ?

**Comment by yanndegat** [comment]
ok

thank you very much @gaetanfl 

merging this PR

**Pull request merged**
